# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pgrokd < Formula
  desc "Server introspected tunnels to localhost a fork from pgrok."
  homepage "https://github.com/jerson/pgrok"
  version "3.2.7"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/jerson/pgrok/releases/download/v3.2.7/pgrokd_3.2.7_MacOS_arm64.tar.gz"
      sha256 "5949642b4cb52243d339cdaec56ec2f3cf03338f178db3e3c953d6b368bdf42f"

      def install
        bin.install "pgrokd"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jerson/pgrok/releases/download/v3.2.7/pgrokd_3.2.7_MacOS_x86_64.tar.gz"
      sha256 "6072044d01b83f2b07674cb47c69fa1eba2238d43dba897e60c30f87eef1f270"

      def install
        bin.install "pgrokd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jerson/pgrok/releases/download/v3.2.7/pgrokd_3.2.7_Linux_arm64.tar.gz"
      sha256 "cc1ab0953f9616ca1508d777884425ca2a947e999e4fc61380ac58002a525ee9"

      def install
        bin.install "pgrokd"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jerson/pgrok/releases/download/v3.2.7/pgrokd_3.2.7_Linux_x86_64.tar.gz"
      sha256 "84d74978b692eaa65956b71a2718a70bd9a4e3de7795c938d58d2c2c83e317ce"

      def install
        bin.install "pgrokd"
      end
    end
  end

  test do
    system "#{bin}/pgrokd", "-v"
  end
end
