# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pgrok < Formula
  desc "Introspected tunnels to localhost a fork from pgrok."
  homepage "https://github.com/jerson/pgrok"
  version "3.2.2"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jerson/pgrok/releases/download/v3.2.2/pgrok_3.2.2_MacOS_x86_64.tar.gz"
      sha256 "18ecaacd568c12060b715577080f0f9cb254b8d031b8df51959189d99b394bb9"
    end
    if Hardware::CPU.arm?
      url "https://github.com/jerson/pgrok/releases/download/v3.2.2/pgrok_3.2.2_MacOS_arm64.tar.gz"
      sha256 "d881c98fe7380f092b2797cbdee6f41dadc3be36be76b1971fa40e4e70a33d49"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/jerson/pgrok/releases/download/v3.2.2/pgrok_3.2.2_Linux_x86_64.tar.gz"
      sha256 "b78e03bcd34268ea64ef87045417aab45eb29fad5785663cb35457eab1467710"
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/jerson/pgrok/releases/download/v3.2.2/pgrok_3.2.2_Linux_armv6.tar.gz"
      sha256 "5013ddb48d42d4775b708b0e7c0a23e0d0d6762e477b6ba1f7acd37e6a0146de"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jerson/pgrok/releases/download/v3.2.2/pgrok_3.2.2_Linux_arm64.tar.gz"
      sha256 "23939f32caf86c54ae5b1c86ca508d2a709a69309cdd7b25609f9c03a9387825"
    end
  end

  def install
    bin.install "pgrok"
  end

  test do
    system "#{bin}/pgrok", "-v"
  end
end
