# This file was generated by GoReleaser. DO NOT EDIT.
class Pgrokd < Formula
  desc "Introspected tunnels to localhost a fork from pgrok."
  homepage "https://github.com/jerson/pgrok"
  version "3.0.9"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/jerson/pgrok/releases/download/v3.0.9/pgrokd_3.0.9_Darwin_x86_64.tar.gz"
    sha256 "f1e6e91f040a559a5304e65883f36b3632736482e93c8afadb5dfa68bd78eb1c"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/jerson/pgrok/releases/download/v3.0.9/pgrokd_3.0.9_Linux_x86_64.tar.gz"
      sha256 "1ac87ebee61b1ad8c712290ebb75827eee871d370982c24a17c37eafe6b5ef9e"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jerson/pgrok/releases/download/v3.0.9/pgrokd_3.0.9_Linux_arm64.tar.gz"
        sha256 "8cd40e1d166e94475ba6358355dd68928545e1f5ca11e5977f2bdbd9ea90048a"
      else
        url "https://github.com/jerson/pgrok/releases/download/v3.0.9/pgrokd_3.0.9_Linux_armv6.tar.gz"
        sha256 "a5308d39d2eb3c6f6f73c0c9c65ed8382055b08fc8c5603319071663419d8346"
      end
    end
  end

  def install
    bin.install "pgrok"
    bin.install "pgrokd"
  end

  test do
    system "#{bin}/pgrokd -v"
  end
end
