# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pgrok < Formula
  desc "Introspected tunnels to localhost a fork from pgrok."
  homepage "https://github.com/jerson/pgrok"
  version "3.2.5"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jerson/pgrok/releases/download/v3.2.5/pgrok_3.2.5_MacOS_x86_64.tar.gz"
      sha256 "c810a2388f0bd7f6d44b7d122c34984cd4aaf285c0632ca57242cbdd8f8f8f43"
    end
    if Hardware::CPU.arm?
      url "https://github.com/jerson/pgrok/releases/download/v3.2.5/pgrok_3.2.5_MacOS_arm64.tar.gz"
      sha256 "693d56a28c97df91e2e74ed334a58c618679fdb8ef558347e221e943d57c5193"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/jerson/pgrok/releases/download/v3.2.5/pgrok_3.2.5_Linux_x86_64.tar.gz"
      sha256 "2d83704d21e3c26d3bf0684ed9d1a7e491f9f04235837667fb7449e86c609f38"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jerson/pgrok/releases/download/v3.2.5/pgrok_3.2.5_Linux_arm64.tar.gz"
      sha256 "1a8b72cd00835c9f631ab101a47558fb4ea85e3f0c83403d5c63d84d2fc7a19a"
    end
  end

  def install
    bin.install "pgrok"
  end

  test do
    system "#{bin}/pgrok", "-v"
  end
end
