# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pgrok < Formula
  desc "Introspected tunnels to localhost a fork from pgrok."
  homepage "https://github.com/jerson/pgrok"
  version "3.2.8"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jerson/pgrok/releases/download/v3.2.8/pgrok_3.2.8_MacOS_x86_64.tar.gz"
      sha256 "659ba808ef2b0f19802573b0b39ad556c7dad0d6e1ab0681a1dfde5d567fc9ed"

      def install
        bin.install "pgrok"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jerson/pgrok/releases/download/v3.2.8/pgrok_3.2.8_MacOS_arm64.tar.gz"
      sha256 "af22d150c14e2b4bdeb6c7bece48aaee8acfced97b1b5ea400467722401c8fad"

      def install
        bin.install "pgrok"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/jerson/pgrok/releases/download/v3.2.8/pgrok_3.2.8_Linux_x86_64.tar.gz"
      sha256 "383641e232de99ac46f9722c347ed20487b32b3f5493cd86e14cc142718078df"

      def install
        bin.install "pgrok"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jerson/pgrok/releases/download/v3.2.8/pgrok_3.2.8_Linux_arm64.tar.gz"
      sha256 "459c74a6b8894acc99697f86b3759869534b0ffed094ec50963405460f11233e"

      def install
        bin.install "pgrok"
      end
    end
  end

  test do
    system "#{bin}/pgrok", "-v"
  end
end
