# This file was generated by GoReleaser. DO NOT EDIT.
class ScreenshotTools < Formula
  desc "Screenshot tools for take and merge."
  homepage "https://github.com/jerson/screenshot-tools"
  version "0.1.11"
  bottle :unneeded

  if OS.mac?
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/jerson/screenshot-tools/archive/v0.1.11.tar.gz"
      sha256 "190258e7a1af78e711764e1538249bf532cb206b58bae3e8c90f5d1bb04185fd"
    end
  end
  
  head "https://github.com/jerson/screenshot-tools.git"
  
  depends_on "go"

  def install
    ENV["CGO_ENABLED"] = "1"
    ENV["GO111MODULE"] = "off"
    ENV["GOPATH"] =  ENV["GOPATH"] || "#{ENV["HOME"]}/go"
    system "go", "get", "-u", "github.com/gobuffalo/packr/v2/packr2"
    ENV["GO111MODULE"] = "on"
    ENV["PATH"] = PATH.new( "#{ENV["GOPATH"]}/bin" , ENV["PATH"])
    system "go generate"
    system "packr2"
    system "go", "build", "-o", "screenshot-tools"
    bin.install "screenshot-tools"
  end

  test do
    system "#{bin}/screenshot-tools", "--version"
  end
end
